#image: registry.gitlab.com/pages/hugo/hugo_extended:latest

image: alpine:edge

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk -U upgrade
  - apk add --update --no-cache go git hugo
  - hugo version

pages:
  script:
  - hugo --minify --enableGitInfo
  artifacts:
    paths:
    - public
  only:
  - master
