image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk add --update --no-cache git
  - hugo version

deploy:
  script:
  - hugo --minify --enableGitInfo
  artifacts:
    paths:
    - public
  only:
  - master
