baseurl: "https://www.kangeko.my.id"
title: Kang Eko
theme: pargo
googleAnalytics: UA-54154424-1
disqusShortname: ekofidias

permalinks:
  post: "/blog/:slug/"
  page: "/:slug/"

params:
  author: Eko Fidia's
  description: "Hello, saya Eko. Blog ini belum jadi. Sabar ya..."

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - ":git"
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date
  expiryDate:
    - expiryDate

menu:
  main:
    - identifier: about
      name: Menu
      url: /
      weight: 1
    - identifier: art
      name: About
      url: /about/
      weight: 2
    - identifier: twitter
      name: Twitter
      url: ""
      weight: 3
    - identifier: github
      name: Github
      url: "https://github.com/LapakArduino"
      weight: 4
    - identifier: rss
      name: RSS
      url: ""
      weight: 5

markup:
  goldmark:
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false